### PR TITLE
Delete opt-in record after successful registration

### LINKED ISSUE #14: Add possibility to delete opt-in records after validation
For data privacy issues it may be good to not have any personal data in the TYPO3 database.
So, it would be very cool to set a flag (in finisher or globally) to delete the records after validation.

### PR DESCRIPTION
**Pull request by linawolf**
resolves #14

### CODE REVIEW

**Comment by linawolf** [comment]
@danielkestler do you have any feedback on this Pull Request?

**Comment by danielkestler** [comment]
To be honest, I just don't have any time for it, sorry. Maybe you'd like to become owner of this extension?

**Comment by linawolf** [comment]
@danielkestler I would be willing to take it over as it is very helpful but needs some Love, Tests and TYPO3 v12 support

**Comment by danielkestler** [comment]
Thank you, that would be great and indeed, it does not get much love by our agency as we are not using it actively in any project anymore. Will try to transfer it to you!

**Comment by danielkestler** [comment]
@linawolf Transferring currently does not work, as you already have a forked repository of this one ;-)

**Comment by linawolf** [comment]
Could we merge my pull requests first, then I can delete my gork

**Comment by danielkestler** [comment]
Yes, merged all open PRs.

**Comment by linawolf** [comment]
Deleted my fork

**Pull request merged**
